sources:
  - name: bsky_posts_fr
    database: digepizcde
    schema: bsky_posts
    tables:
      - name: grippe
      - name: rhume
      - name: fievre
      - name: courbature
      - name: llm_hints

  - name: bsky_posts_de
    database: digepizcde
    schema: bsky_posts
    tables:
      - name: grippe
      - name: schnupfen
      - name: fieber
      - name: muskelschmerzen
      - name: llm_hints

models:
  - name: bsky_all_posts_fr
    sources:
      - source('bsky_posts', 'grippe')
      - source('bsky_posts', 'rhume')
      - source('bsky_posts', 'fievre')
      - source('bsky_posts', 'courbature')

  - name: bsky_post_fr_llm_filtered
    sources:
      - ref('bsky_all_posts_fr')
      - source('bsky_posts_fr', 'llm_hints')

  - name: bsky_all_posts_de
    sources:
      - source('bsky_posts', 'grippe')
      - source('bsky_posts', 'Schnupfen')
      - source('bsky_posts', 'Fieber')
      - source('bsky_posts', 'Muskelschmerzen')
