name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or your main branch name
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read # Required to checkout the code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # or your registry (e.g., gcr.io, ecr.amazonaws.com)
          username: ${{ github.repository_owner }} # or your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Store this in GitHub secrets

      - name: Build and Push Docker Image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: . # Location of the Dockerfile
          file: orchestration/Dockerfile # Name of the Dockerfile
          push: true
          tags: |
            docker.io/${{ github.repository_owner }}/digepi_bsky:latest
            
# docker.io/${{ github.repository_owner }}/bsky-housekeeping:${{ github.sha }} # Tag with commit SHA for traceability

 #     - name: Image digest
 #       run: echo "Digest: ${{ steps.build-push.outputs.digest }}"